# Etapa de construcción
FROM node:16 as builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . ./ 

RUN npm run build

# Etapa de producción
FROM nginx:latest as final

# Copia los archivos de la etapa de construcción al directorio de Nginx
COPY ./nginx/default.conf /etc/nginx/conf.d/default.conf
COPY --from=builder /app/dist /usr/share/nginx/html

# Exponer el puerto 80
EXPOSE 80
