version: '3'

services:
  mongo:
    image: "mongo"
    container_name: 'MongoDB'
    restart: always
    volumes:
      - volume_mongo:/data/db      
    ports:
      - "27017:27017"
  backend:
    build: "./backend"
    container_name: 'backend'
    restart: always
    ports:
      - "2024:2024"

  frontend:
    build: "./frontend"
    container_name: 'frontend'
    restart: always
    ports:
      - "5173:5173"
    depends_on:
      - backend
    
volumes:
  volume_mongo: