apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-ruta
  namespace: kafka
spec:
  selector:
    matchLabels:
      role: grpc-ruta
  replicas: 1
  template:
    metadata:
      labels:
        role: grpc-ruta

    spec:
      containers:
      - name: grpc-client
        image: bekinggo/grpc_client
        ports:
        - containerPort: 3002
      - name: grpc-server
        image: bekinggo/grpc_server
        ports:
        - containerPort: 3001
---
apiVersion: v1
kind: Service
metadata:
  name: service-grpc
  namespace: kafka
spec:
  type: LoadBalancer
  ports:
  - name: grpc-client-port
    port: 3002
    targetPort: 3002
  - name: grpc-server-port
    port: 3001
    targetPort: 3001
  selector:
    role: grpc-ruta