version: '3'
services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyPass123
      MYSQL_DATABASE: dbso1py1
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - volumen1:/var/lib/mysql

    networks:
      - py1_network

  backend:
    build: "./backend"
    container_name: 'backend'
    restart: always
    ports:
      - "8080:8080"
    networks:
      - py1_network

  frontend:
    build: "./frontend"
    container_name: 'frontend'
    restart: always
    ports:
      - "80:80"
    networks:
      - py1_network
  
networks:
  py1_network:
    

volumes:
  volumen1: