
version: '3'

services:
  mydb:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: MyPass123
      MYSQL_DATABASE: dbso1py1
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  api:
    build: "./backend"
    container_name: 'backend'
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mydb
    links:
      - mydb


  front:
    build: "./frontend"
    container_name: 'frontend'
    ports:
      - "80:80"
    restart: always
    depends_on:
      - api


  volumes:
    mydb_data:
      external: false


