# Etapa de construcción
FROM node:16 as builder

WORKDIR /app

COPY package.json ./
COPY package-lock.json ./

RUN npm install

COPY . ./ 

RUN npm run build

# Etapa de producción
FROM nginx:latest

# Copiamos los archivos de construcción del cliente a la imagen de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html

# Exponemos el puerto 80
EXPOSE 80

# Comando para iniciar el servidor Nginx
CMD ["nginx", "-g", "daemon off;"]
