FROM node:21.6.1

# Create app directory
WORKDIR /back

# Install app dependencies
COPY package*.json ./

COPY package-lock.json ./

# Bundle app source
RUN npm install

COPY . ./

EXPOSE 2024

CMD [ "node", "index.js" ]