
FROM node:21.6.1

# Create app directory
WORKDIR /frontend

# Install app dependencies
COPY package*.json ./

COPY package-lock.json ./

# Bundle app source
RUN npm install

COPY . ./

EXPOSE 3000

CMD [ "npm", "start" ]