FROM rust:latest as builder
WORKDIR /usr/src/app
COPY . .
RUN cargo build --release
FROM ubuntu:latest
RUN apt-get update && apt-get install -y libssl-dev
COPY --from=builder /usr/src/app/target/release/rust-client /usr/local/bin/rust-client
EXPOSE 8000
CMD ["rust-client"]

# docker build -t bekinggo/rust_client .
# docker push bekinggo/rust_client
# docker run -p 8000:8000 bekinggo/rust_client